client/src/components/AlumniDirectory.js, client/src/components/Profile.js
=> Alum Directory Component

client/src/components/Profile.js
Todo:
Implement LinkedIn update functionality
Determine what other functionality we want for users that can edit the profile
(currently has placeholder buttons for LinkedIn and Image update)
=> Created profile card component using semantic ui

server/models/alumniSchema.js, server/models/studentSchema.js, server/routes/utilMongoose.js
utilMongoose now organized by alumni, student, user, and all
Models:
alumniSchema (modified)
Now has ImageURL key for profile pictures. Defaults to a blank profile placeholder
This image is currently hosted by Pixabay and is free to use without attribution by the Pixabay license
studentSchema
imageURL - String, default (same as alumniSchema)
name - String, required
email - String, required
grade - Number, required
timeZone - String, required
TODO: requests, issuesLiked (need their corresponding models)
New Endpoints:
GET /student - responds with one student record, selected by email
body: email
GET /allStudent - responds with all student records
POST /addStudent - adds a new student record to Student and User collection
body: email, name, grade, timezone, password
GET /data/clear/Student …
=> added profile image, organized utilMongoose, added student routes and model

server/app.js, server/models/requestSchema.js, server/routes/requests.js, server/routes/utilMongoose.js
Models
requestSchema:
student - studentSchema._id
alumni - alumniSchema._id
time - string, required
zoomLink - string, required (Note: this means an alumni must have a zoomLink before they can be requested) - maybe have a form that pops up upon first login?
topic - string, required
status - string enum ['Awaiting Confirmation',
'Completed',
'Rejected',
'Feedback Provided']
(The string must match one of these categories or it will fail validation)
intro - string
notes - string
Endpoints
POST /request/addRequest - adds a request to the Requests collection
body: student_email, alumni_email, time, topic, status, intro, note
(emails will be the easiest way to identify users - because the alumni is an object on the frontend, we will have access to its email even if the user won't)
GET …
=> created request model, endpoint, utils

client/src/components/Signup.js, server/app.js, server/models/alumniSchema.js, server/models/studentSchema.js, server/routes/index.js, server/routes/students.js
Frontend:
* Added Student Registration form
Backend:
* Added post route to add student
* Added login case for returning student details upon successful login
=> Student Registration Route

server/app.js
Super small PR to remove setting up this router twice!
=> removed duplicate router hookup

client/src/App.js, client/src/components/AlumniDirectory.js, server/routes/alumni.js
See PR #15 (Now closed) to see most of the scope of the changes
In this PR, unnecessary async functions have been made synchronous, profile generation has been moved to a method, and the display now updates in real time based upon search values. The best way to show this behavior would be a live demo.
=> fully functional search

client/src/App.js, client/src/components/LoginForm.js, server/app.js, server/routes/alumni.js, server/routes/index.js, server/routes/students.js, server/routes/user.js
new routes for users: user.js
added userRoutes to app.js
Modified: /login - the cookie is now created once the profile details have been gathered - this has changed nothing behavior wise but allows the cookie to contain more useful info
body: 
- email: string
returns matching object
LoginForm is unchanged from its original form
App.js now has student routes
//TODO: Fix profile routes - currently broken because profile and role aren't props
// This is ok for now because they will be overhauled soon
Default route switched from null to Home - this makes the transition from login to home less jarring
App.js fetches role and profile from the cookie! - if user is logged with valid token, the jwt will be parsed and used to set states
logout now clears local storage - this will be useful if we …
=> Cookies! and StudentRoutes

server/helpers/timezoneHelpers.js, server/models/alumniSchema.js, server/package-lock.json, server/package.json, server/routes/alumni.js, server/routes/utilMongoose.js, server/test/timezoneHelpers.test.js
* Added timezoneHelpers module that takes strips or applies timezone to an array of timeSlots. timeSlots have shape
```
{
id: 'Sunday-400',
day: 'Sunday',
time: 400
}
```
=> Backend Timezone adjustment helper methods and unit tests

server/routes/utilMongoose.js
LoremPicsum seems to no longer be hosting the images at the ids we specified.
I decided to switch over to placedog because it offers the same functionality but more reliably serves the images
=> Change image host for seeded images

client/src/components/RequestModal.js, server/helpers/timezoneHelpers.js, server/routes/helpers/emailHelpers.js, server/routes/requests.js
Changes:
* Alumni/mentor gets email when a new call request is made
* Both mentee and mentor gets email when a call is confirmed
=> Email integration for request interactions

client/src/components/NewsFeed.js, server/models/newsSchema.js, server/routes/alumni.js
Added news item creation in topic preferences
Added enum for new topics in newsSchema
Added create method for new topics in NewsFeed component
=> New Topics posts in feed

client/src/components/Header.js, client/src/components/LoginForm.js, server/models/userSchema.js, server/routes/helpers/emailHelpers.js, server/routes/index.js
Changes:
* Users can provide an email if they forget their password. This sends an email with a token, that can be used to request a temporary password
* Users can change their password if they have a logged in session
Screens:
* Forgot password --> 
( Submission enabled on valid email input )
( Clicking button in email makes get request with token + email as params )
( Confirmation html upon successfully requesting temporary password )
( Email containing temporary password ) 
* Changing password -->
=> added ability to request new temp password and change password

client/src/App.js, client/src/components/AlumniMentorship.js, client/src/components/AlumniProfile.js, client/src/components/TimePreferencesModal.js
Removed the meeting related buttons from Alumni Profile
Otherwise, more or less a movement of code from one file to another
=> Meeting Settings Tab

client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/StudentMentorship.js, server/models/requestSchema.js, server/routes/requests.js
=> Extended Feedback, Added pre-meeting note

client/src/components/AlumniProfile.js, client/src/components/StudentProfile.js
Changes:
* Image update and interests update standardized to mimic that of alumni profile
Screens:
=> Image Update and interests update from student profile

client/src/apis.js, client/src/components/CollegeSelectionModal.js, client/src/components/CompanySelectionModal.js, client/src/components/ImageSelectModal.js, client/src/components/LocationSelectionModal.js, client/src/components/MajorSelectionModal.js, client/src/components/Signup.js, server/routes/alumni.js, server/routes/image.js, server/routes/students.js
Changes:
* Alumni and Student are both required to upload an image during registrations
* Alumni must also provide at least one topic of consultancy and a zoom meeting link
Screens:
=> Image required for sign up + Alumni must provide one topic of consultancy + zoomLink

client/src/App.js, client/src/components/AlumniNetworking.js, server/models/conversationSchema.js, server/routes/conversations.js
=> Added networking view, get route for conversations

client/src/components/AlumniNetworking.js, client/src/components/ConversationModal.js, client/src/components/Header.js, server/models/conversationSchema.js, server/routes/conversations.js
(Moment doesn't default to UTC so this shows me in the process of fixing it - also it seems like the timestamps are a little off, but not by enough to be problematic)
Also features a UI change - I found semantic UI comments, which fixed literally every problem I had with feed
=> Conversation Modal

client/src/components/Signup.js
=> added gradYear validation

client/src/App.js, client/src/components/admin_dashboard/CollegesList.js, client/src/components/admin_dashboard/FeedbackModal.js, client/src/components/admin_dashboard/MergeModal.js, server/routes/admin.js, server/routes/utilMongoose.js
=> added college list and multipurpose merge modal

client/src/App.js, client/src/components/StudentMentorship.js, client/src/components/admin_dashboard/CollegesList.js, client/src/components/admin_dashboard/FeedbackModal.js, client/src/components/admin_dashboard/MergeModal.js, client/src/components/admin_dashboard/ProfileList.js, server/routes/admin.js, server/routes/utilMongoose.js
Approval/ Suspension only shows one button, saves search filters
Promotion shows moderator as meta tag, saves search filters
Feedback uses semantic UI Accordion
=> Approval Toggle, promote to moderator, and feedback modal

client/src/App.js, client/src/components/StudentMentorship.js, client/src/components/admin_dashboard/CollegesList.js, client/src/components/admin_dashboard/FeedbackModal.js, client/src/components/admin_dashboard/MergeModal.js, client/src/components/admin_dashboard/ProfileList.js, server/app.js, server/models/adminSchema.js, server/routes/admin.js, server/routes/index.js, server/routes/utilMongoose.js
This one ended up being pretty chunky - but hopefully, react hooks kept it pretty readable!
It's more or less 2 parts: General Admin role setup (very useful for testing), and the Alumni/Student Tabs
New Model: AdminSchema - name, user, timezone. 
Allows for direct login to Admin Dashboard, along with changes to login
Added tags to mongoose init to remove deprecation warnings
New routes: admin.js (all alumni and all students, one) with role checker
To prevent further clutter in the components folder, created admin_dashboard folder
Created ProfileList, a component that kills two similar looking birds with one stone
Uses React's functional components, which should hopefully make it look cleaner. React doesn't actually know what dependencies it wants for each useEffect though, so don't …
=> Alumni and Student Tab setup

client/src/App.js, client/src/components/admin_dashboard/NewSchoolModal.js, client/src/components/admin_dashboard/SchoolImageModal.js, client/src/components/admin_dashboard/SchoolsList.js, server/routes/admin.js, server/routes/image.js
TODO: Create Add school Modal
Note: In the process of writing this module, I once again ran into the image upload bug - my theory (though it may not be a good one) is that multiparty is not a good form parser. While the makeCallWithImage API is successful and contains an image, the parser does not get the file quickly enough.
Image Select Modal works because its route has to hash an email before accessing the file, which adds enough delay to find the image and upload it.
New school and modal:
=> SchoolList setup

server/routes/utilMongoose.js
PATCH /util/promoteAdmin/alumniId/ - body: {id : Alumni ID}
PATCH /util/promoteAdmin/email/ - body: {email : User Email}
PATCH /util/promoteAdmin/userId/ - body: {id : user ID}
=> Util routes for admin promotion

client/src/App.js, client/src/components/Header.js, client/src/components/admin_dashboard/NewSchoolModal.js, client/src/components/admin_dashboard/SchoolImageModal.js, client/src/components/admin_dashboard/SchoolsList.js, server/app.js, server/models/collegeRepSchema.js, server/models/userSchema.js, server/routes/admin.js, server/routes/collegeRep.js, server/routes/image.js, server/routes/index.js, server/routes/utilMongoose.js
Created College Rep Schema, with same fields as admin schema + college reference
To add a college rep to the app, send a GET request to the server at /util/newCollegeRep
Also includes a hotfix for admin, where alumni can now switch to the admin dashboard from any alumni tab (rather than just the newsfeed)
NOTE: Current base is development, not develop - After review I will switch base to develop and merge, and delete development
=> College Rep portal

client/src/App.js, client/src/components/Header.js, server/routes/alumni.js, server/routes/students.js
=> hotfix for logout, made button layout mobile friendly

client/src/App.js, client/src/components/Header.js, server/routes/index.js
* Was broken because frontend no longer has access to email from user record
=> Fix change password API

client/src/apis.js, server/routes/index.js, server/routes/utilMongoose.js
* A user is denied login if their account is unapproved/unverified
* Seeding database defaults to email verified for dummy users and randomly approves alumni/students
=> Guard login by verified/approval

client/src/components/AlumniContactModal.js, client/src/components/CollegeShortlistModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/TimePreferencesModal.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js
Fixed submit button to bar user from submitting multiple times while the submit processes.
=> Submit Bug

client/src/components/AlumniContactModal.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/routes/index.js
* Not a fan, but early-stage adoption FTW
=> Allow unapproved students/alumni to login (for now)

client/src/components/AlumniContactModal.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js
Note: The OFI logo will actually be at the top.
=> Include branding in OFI email templates

client/src/components/AlumniContactModal.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TimeZoneDropdown.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js
Collected from [here](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets)
=> Add Archetypal locations to timezone options

client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/StudentMentorship.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TimeZoneDropdown.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/models/requestSchema.js, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js, server/routes/requests.js
* Alumni are no longer required to provide a topic, a zoom meeting link when they sign up
* A student can submit a request without a time selected, but must now select a topic or leave a note
=> Rollback enforcing time, topic, and zoom meeting link for registration and requests

client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/StudentMentorship.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TimeZoneDropdown.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/models/requestSchema.js, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js, server/routes/requests.js
=> Explicitly call out High School Graduation Year for Alumni Registration

client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/AlumniProfile.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/StudentMentorship.js, client/src/components/StudentProfile.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TimeZoneDropdown.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, server/app.js, server/models/requestSchema.js, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js, server/routes/requests.js
=> Prevent Rendering empty interests section for profiles in View-only mode

client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/AlumniProfile.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/StudentMentorship.js, client/src/components/StudentProfile.js, client/src/components/TermsOfAgreementModal.js, client/src/components/TimePreferencesModal.js, client/src/components/TimeZoneDropdown.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, package-lock.json, package.json, server/app.js, server/models/requestSchema.js, server/package.json, server/routes/helpers/emailBodyBuilder.js, server/routes/index.js, server/routes/requests.js
* After running an `npm i` in root directory, using `npm run dev` should track code changes in both client and server directory to reload the app
=> Allow live server-sdie reloading during development

client/src/App.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniProfile.js, client/src/components/DeleteAccountModal.js, client/src/components/LocationUpdateModal.js, client/src/components/StudentProfile.js, server/routes/alumni.js, server/routes/students.js
Screens:
The delete action cleans up any record in news, requests, users, and alumni/students collections that is associated with the user being deleted.
=> Allow Students and Alumni to delete profiles

client/src/App.js, server/package-lock.json, server/package.json, server/routes/index.js
This reverts commit fc7b1f084ef49470633547619686488f529ce1f3.
=> Revert "comitting local changes before pulling ofi-release"

client/src/components/AlumniDirectory.js, client/src/components/AlumniOpportunities.js, client/src/components/Footer.js, client/src/components/NewsFeed.js, client/src/components/RequestModal.js, client/src/components/carousels/PollCarousel.js, server/routes/requests.js
Plus, small bonus fixes (see commits)
=> Polls/Announcements and News are split into subtabs in Home

client/src/App.js, client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/AlumniNetworking.js, client/src/components/AlumniOpportunities.js, client/src/components/ConversationModal.js, client/src/components/DeleteAccountModal.js, client/src/components/Footer.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/LoginForm.js, client/src/components/Navbar.js, client/src/components/NewsFeed.js, client/src/components/RequestModal.js, client/src/components/StudentMentorship.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, client/src/components/carousels/PollCarousel.js, server/routes/alumni.js, server/routes/requests.js, server/routes/students.js
Add a notification bubble for new messages received, and new requests received for alumni. This should update real-time.
Add notification bubble for confirmed requests for students
=> Add icons to menu and notification bubbles

client/src/App.js, client/src/components/AlumniContactModal.js, client/src/components/AlumniDirectory.js, client/src/components/AlumniMentorship.js, client/src/components/AlumniNetworking.js, client/src/components/AlumniOpportunities.js, client/src/components/ConversationModal.js, client/src/components/DeleteAccountModal.js, client/src/components/Footer.js, client/src/components/ImageSelectModal.js, client/src/components/ImageUpdateModal.js, client/src/components/InterestsUpdateModal.js, client/src/components/LocationUpdateModal.js, client/src/components/LoginForm.js, client/src/components/Navbar.js, client/src/components/NewsFeed.js, client/src/components/RequestModal.js, client/src/components/Signup.js, client/src/components/StudentMentorship.js, client/src/components/TopicPreferencesModal.js, client/src/components/ZoomUpdateModal.js, client/src/components/alumni_profile_update_modals/CollegeUpdateModal.js, client/src/components/alumni_profile_update_modals/CompanyUpdateModal.js, client/src/components/alumni_profile_update_modals/JobTitleUpdateModal.js, client/src/components/alumni_profile_update_modals/MajorUpdateModal.js, client/src/components/carousels/PollCarousel.js, server/models/userSchema.js, server/routes/alumni.js, server/routes/requests.js, server/routes/students.js
Send server-side error that is displayed on toast
=> Inform user if an account exists with provided email

server/routes/admin.js, server/routes/helpers/emailHelpers.js
Users get an email notification when their accounts have been approved.
=> Send users an email when their account has been approved by an admin

client/src/components/Header.js
Allows toasts from embedded modal to be visible
=> Hotfix - Remove blurring in Login modal
